### PR TITLE
perf(metarepos): reuse mrpb.StorageNodeUncommitReport while changed

### PR DESCRIPTION
**Pull request by ijsong**
### What this PR does

This change makes mrpb.StorageNodeUncommitReport is reused when it is replaced with a new one.
Previous PR, #446, introduced a pool for mrpb.StorageNodeUncommitReport. However, the old
StorageNodeUncommitReport stored to reportContext was not reused, and this PR improves it.

To release the StorageNodeUncommitReport registered to reportContext, some methods of reportContext
are changed:

- (*reportContext).getReport returns a value of StorageNodeUncommitReport rather than a pointer. It
  makes releasing the StorageNodeUncommitReport happen at any time.
- add (*reportContext).swapReport to set a new StorageNodeUncommitReport and get the old one
  simultaneously.
- getReport and swapReport return the boolean result to indicate whether the result report is zero
  value.

BenchmarkSwapReport evaluates the performance improvements of this change.

- getAndSavePtr: Previous implementation.
- getAndSave: Call getReport and saveReport.
- swap: Call swapReport.

```
BenchmarkSwapReport/getAndSavePtr-16             5947423               207.8 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6220454               198.7 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6133489               198.5 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6131910               199.8 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             5592459               201.6 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6180243               200.1 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6172357               199.2 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6211966               198.6 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6095289               198.3 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSavePtr-16             6043491               197.6 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6143407               200.6 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                5938540               203.6 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6162986               198.5 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6172598               197.8 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6105918               197.0 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6077460               196.5 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                5953898               197.8 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6131799               199.9 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6139296               200.5 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/getAndSave-16                6115653               198.5 ns/op            32 B/op          1 allocs/op
BenchmarkSwapReport/swap-16                     35501544                33.83 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     35982945                34.05 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     36518960                34.21 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     34620783                34.52 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     35967453                33.88 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     36135454                34.17 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     34492548                35.16 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     35581888                34.14 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     32028504                33.78 ns/op            0 B/op          0 allocs/op
BenchmarkSwapReport/swap-16                     36024037                33.94 ns/op            0 B/op          0 allocs/op
```

### CODE REVIEW

**Comment by ijsong** [comment]
Current dependencies on/for this PR:
* main
  * **PR #532** <a href="https://app.graphite.dev/github/pr/kakao/varlog/532" target="_blank">Graphite</a> 
    * **PR #533** <a href="https://app.graphite.dev/github/pr/kakao/varlog/533" target="_blank">Graphite</a> 
      * **PR #534** <a href="https://app.graphite.dev/github/pr/kakao/varlog/534" target="_blank">Graphite</a> 
        * **PR #536** <a href="https://app.graphite.dev/github/pr/kakao/varlog/536" target="_blank">Graphite</a> 
          * **PR #537** <a href="https://app.graphite.dev/github/pr/kakao/varlog/537" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/537?utm_source=stack-comment).

**Review by hungryjang — APPROVED** [review]
That's something I didn't even think of. Is there any way to make [diff.UncommitReports](https://github.com/kakao/varlog/blob/519cd60f2e0bffdcba5ee4f2af4f57548fa49220/internal/metarepos/report_collector.go#L666) using pool?

**Comment by ijsong** [comment]
> That's something I didn't even think of. Is there any way to make [diff.UncommitReports](https://github.com/kakao/varlog/blob/519cd60f2e0bffdcba5ee4f2af4f57548fa49220/internal/metarepos/report_collector.go#L666) using pool?

Using `sync.Pool` for `diff.UncommitReports` looks promising, but the variable length makes using the pool difficult.
However, there are a few tricks you can try:
- Pooling of growable diff.UncommitReports: there will usually be an upper bound on the length.
- Use hard limit: In rare cases where the length of diff.UncommitReports can be increased than expected; we can shrink and reclaim it to the pool.
- Use reuse cycle: When the number of reusing the diff.UncommitReports is greater than the given parameter; we can discard it.

I am not convinced the above logic works well. However, some of them are being used for other open-source projects.

**Comment by ijsong** [comment]
@ijsong started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/537).

**Comment by ijsong** [comment]
@ijsong merged this pull request with [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/537).

**Pull request merged**
