### PR TITLE
refactor(all): use atomic types

### PR DESCRIPTION
**Pull request by ijsong**
### What this PR does

Use new atomic types instead of old atomic functions to avoid misuse of variables.

### CODE REVIEW

**Comment by ijsong** [comment]
Current dependencies on/for this PR:
* main
  * **PR #444** <a href="https://app.graphite.dev/github/pr/kakao/varlog/444" target="_blank">Graphite</a> 
    * **PR #411** <a href="https://app.graphite.dev/github/pr/kakao/varlog/411" target="_blank">Graphite</a> 
      * **PR #412** <a href="https://app.graphite.dev/github/pr/kakao/varlog/412" target="_blank">Graphite</a> 
        * **PR #413** <a href="https://app.graphite.dev/github/pr/kakao/varlog/413" target="_blank">Graphite</a> 
          * **PR #414** <a href="https://app.graphite.dev/github/pr/kakao/varlog/414" target="_blank">Graphite</a> 
            * **PR #445** <a href="https://app.graphite.dev/github/pr/kakao/varlog/445" target="_blank">Graphite</a> 
              * **PR #446** <a href="https://app.graphite.dev/github/pr/kakao/varlog/446" target="_blank">Graphite</a> 
                * **PR #447** <a href="https://app.graphite.dev/github/pr/kakao/varlog/447" target="_blank">Graphite</a> 
                  * **PR #448** <a href="https://app.graphite.dev/github/pr/kakao/varlog/448" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/448?utm_source=stack-comment).

**Comment by ijsong** [comment]
Current dependencies on/for this PR:
* main
  * **PR #444** <a href="https://app.graphite.dev/github/pr/kakao/varlog/444" target="_blank">Graphite</a> 
    * **PR #411** <a href="https://app.graphite.dev/github/pr/kakao/varlog/411" target="_blank">Graphite</a> 
      * **PR #412** <a href="https://app.graphite.dev/github/pr/kakao/varlog/412" target="_blank">Graphite</a> 
        * **PR #413** <a href="https://app.graphite.dev/github/pr/kakao/varlog/413" target="_blank">Graphite</a> 
          * **PR #414** <a href="https://app.graphite.dev/github/pr/kakao/varlog/414" target="_blank">Graphite</a> 
            * **PR #445** <a href="https://app.graphite.dev/github/pr/kakao/varlog/445" target="_blank">Graphite</a> 
              * **PR #446** <a href="https://app.graphite.dev/github/pr/kakao/varlog/446" target="_blank">Graphite</a> 
                * **PR #447** <a href="https://app.graphite.dev/github/pr/kakao/varlog/447" target="_blank">Graphite</a> 
                  * **PR #448** <a href="https://app.graphite.dev/github/pr/kakao/varlog/448" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/448?utm_source=stack-comment).

**Review by hungryjang — APPROVED** [review]

**Comment by ijsong** [comment]
@ijsong started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/448).

**Comment by ijsong** [comment]
@ijsong merged this pull request with [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/448).

**Pull request merged**
