### PR TITLE
perf(storagenode): check log level

### PR DESCRIPTION
**Pull request by ijsong**
### What this PR does

This PR slightly improves the storage node's performance by checking the log level, making the
logger not make slices in advance.

### CODE REVIEW

**Review by hungryjang — APPROVED** [review]
I don't know how much it helps performance, but it seems to be very poor in usability.

**Comment by ijsong** [comment]
> I don't know how much it helps performance, but it seems to be very poor in usability.

Yeah, it is too micro-optimization to recognize it.

**Comment by ijsong** [comment]
@ijsong started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/411).

**Comment by ijsong** [comment]
@ijsong merged this pull request with [Graphite](https://app.graphite.dev/github/pr/kakao/varlog/411).

**Pull request merged**
